### ISSUE TITLE
Optimization Error for Ag Metal Complex

### ISSUE THREAD

**Issue by deveshawasthi10** [grimme-lab/xtb#1000]
**Describe the bug**
Not able to optimize the Ag metal complex. xtb properly working for Cu and Au complex but when I change the metal from Cu to Ag xtb terminates abnormally.

**To Reproduce**
Steps to reproduce the behaviour:
[full_Ag.txt](https://github.com/grimme-lab/xtb/files/14706701/full_Ag.txt)

This is the xyz file of the molecule which I want to optimize.
1. happens with input full_Ag.txt
2. xtb full_Ag.xyz --opt --verbose --iterations 750
3. run `xtb` 
4. output showing the error:
[full_Ag3.txt](https://github.com/grimme-lab/xtb/files/14715732/full_Ag3.txt)

full Ag3.txt is the output showing the error

**Expected behaviour**
I expected it to properly optimize the Ag geometry as well.

**Additional context**
I also truncated this big system to a smaller model, that system also properly optimized, when the Metals were Cu and Au. But, gave me abnormal termination when I used Ag as the metal.

The system has zero charge. System is closed shell singlet.

**Comment by Albkat** [comment]
Hi,

The issue you're experiencing with transition metals in GFN2-xTB is a known problem, primarily due to the multipole electrostatic term. I recommend using GFN1-xTB instead (I've already tested it with your system, and it works well).

For an overview of xtb’s performance with transition metal complexes, please refer to this [paper](https://doi.org/10.1002/anie.201904021).
