### ISSUE TITLE
Gibbs free energy calculations

### ISSUE THREAD

**Issue by danieleveclani** [grimme-lab/xtb#1043]
Dear Xtb develepers, 

I am one of your users. I am trying to obtain the G value between two interacting molecules using implicit solvent. I have some doubts regarding the calculation of the harmonic contribution and the solvent.

For the DG I use the following equation:

DG = 𝐸 + 𝐺RRHOT + 𝐺solv

𝐺RRHOT = coupled rigid-rotor-harmonic-oscillator approach (vibrational frequency calculations)
𝐺solv = solvation contribution

As E I actually use  total energy obtained from the SUMMARY section of the xtb output file. 

However, I do not understand if this last contribution (total energy) already includes the correction for the solvent (Gsolv). Can you clarify this for me?

Waiting for a kindly reply.

Best,
Daniele Veclani.

**Comment by haneug** [comment]
When you include the ALPB or the GBSA solvation model you already account for Gsolv in the total energy since this is included in your SCF. You can of course also use other (post-SCF) solvation models such as the CPCM-X. In this case, E should be calculated without solvation (so no alpb or gbsa) and then you can add Gsolv from CPCM-X. Note that the GFN methods are parameterized for geometries, frequencies, and non-covalent interactions and not for energies. So you might want to get your E from somewhere else (depending on your application/desired accuracy)
