### ISSUE TITLE
gradient from --grad run is written two times to gradient file

### ISSUE THREAD

**Issue by eljost** [grimme-lab/xtb#110]
**Describe the bug**
When doing a --grad run with the 6.3.0 preview the gradient is written two times to the gradient file. Overall no big deal but probably not intended?!

**To Reproduce**
`xtb [any .xyz file] --grad`

**Expected behaviour**
The gradient entry should only appear once.

**Comment by awvwgk** [comment]
I redid the Turbomole gradient writer in 1e913bf (merged with #106), so this shouldn't be an issue anymore, because the gradient file is now overwritten and not appended.

But it is indeed a bug introduced from the GFN-FF development branch. @sespic, please have a look in the property printout section: `program_main.f90`, l. 855 and l. 870 are duplicates (`ffd08f3`).
