### ISSUE TITLE
Unnecessary buildrequires

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/xtb#1101]
The xtb Meson build system has dependencies on multicharge and dftd4, but the produced binaries don't actually link to these libraries when tblite support is disabled. The dependencies should only be required when tblite support is enabled.

**Comment by marcelmbn** [comment]
This is closely related to the following pull requests:
- https://github.com/grimme-lab/xtb/pull/1081
- https://github.com/grimme-lab/xtb/pull/991

I find it unclear why these dependencies were introduced, as they currently do not seem necessary. Notably, `tblite` already manages these dependencies, as they are required for its core functionalities. Could the contributors involved at that time, @Thomas3R @Albkat @TyBalduf, provide some insights or clarify this decision?

As far as I see, https://github.com/grimme-lab/xtb/pull/1081 at least made the dependencies optional. Still, I definitely agree @susilehtola – I don't really get why we are having unused dependencies.

**Comment by Thomas3R** [comment]
I believe #991 solved a build issue for me at the time. Does #1081 resolve this issue or do you think it is necessary to remove the dependencies completely?

**Comment by susilehtola** [comment]
> Does #1081 resolve this issue or do you think it is necessary to remove the dependencies completely?

#1081 is already merged; the issue exists in the current master branch.

I am a bit annoyed that I went through the trouble to package mstore and multicharge in Fedora only to find that they aren't even used...

**Comment by susilehtola** [comment]
> I believe #991 solved a build issue for me at the time. Does #1081 resolve this issue or do you think it is necessary to remove the dependencies completely?

Yeah it looks like it; I can build xtb on my computer when multicharge and mstore are not installed.

**Comment by marcelmbn** [comment]
@Albkat Let's check again and then remove the optional dependencies again. Btw, this also makes life much easier for the case that `xtb` and `tblite` expect different versions of the two libraries.

**Comment by awvwgk** [comment]
This should be resolved with https://github.com/grimme-lab/xtb/pull/1081 now.

**Comment by marcelmbn** [comment]
> This should be resolved with #1081 now.

I'd contradict. `xtb` doesn't need `multicharge` and `dftd4` at all, only `tblite` uses these dependencies. IMHO, it would be much cleaner to let only `tblite` load its dependencies instead of `xtb` loading them in advance with the assumption that `tblite` would need them. Especially when it comes to different (fixed) versions, this can become problematic.

**Comment by awvwgk** [comment]
If `xtb` can remove imports from `multicharge` and `dftd4` this would be true, but currently have imports which need a direct dependency on those two libraries:

https://github.com/grimme-lab/xtb/blob/88182d28a757ebc9ad4dd669307fb809b48a81c6/src/ptb/calculator.F90#L41

https://github.com/grimme-lab/xtb/blob/88182d28a757ebc9ad4dd669307fb809b48a81c6/src/ptb/twostepscf.F90#L47

https://github.com/grimme-lab/xtb/blob/88182d28a757ebc9ad4dd669307fb809b48a81c6/test/unit/test_ptb.F90#L112

https://github.com/grimme-lab/xtb/blob/88182d28a757ebc9ad4dd669307fb809b48a81c6/src/ptb/coulomb.F90#L35

**Comment by marcelmbn** [comment]
My bad, thanks for hinting! Apparently, I forgot that I used the library solutions for EEQ and the D4 hardness parameters instead of the hard-coded ("legacy") code in `xtb`... 😶‍🌫️
@Albkat, then we should make sure that we are always pointing to the same version as `tblite` does. Leaving these dependencies out would still technically be possible as ptb needs `tblite` and `tblite` needs `multicharge` and `dftd4` in all cases, but this is in some sense also somewhat dirty, as `ptb` should still work in the (hypothetical case) that e.g. `multicharge` is not required anymore by `tblite`.
