### ISSUE TITLE
Compiling xtb on OSX

### ISSUE THREAD

**Issue by hokru** [grimme-lab/xtb#12]
*updated and edited*
Compiling on OSX might interest a few people. 

A few hurdles I ran into:
* needs a fully 'shared' build option as static linking is not really a thing on OSX
* requires at least: `meson configure -Db_lundef=false` (possibly also for gcc)

---

current working version on Catalina and Intel19
grab: https://github.com/hokru/xtb/tree/osx3 (shortened meson config plus PR #40)

```
export FC=ifort CC=icc CXX=icpc
meson setup build_intel -Dstatic=false -Db_lundef=false -Db_asneeded=false
```
There will be an error because of wrong linking flags! Ignore and link yourself:
```
ifort  -o xtb 'xtb@exe/xtb_program_main.f90.o' -qopenmp -mkl libxtb.a  -Wl,-rpath,/INSERT_YOUR_PATH/xtb/build_intel/ libxtb.dylib
```

**Comment by awvwgk** [comment]
Thanks for trying to get an OSX build running.

I got this running for [`dftd4`](https://github.com/dftd4/dftd4). But I don't have a Mac around, so I could only run it on the Travis CI server, which is in principle possible with Intel compilers, but takes some time to setup (having a CI build is a separate issue, of course).

The lines toggling the static linking are here:

https://github.com/grimme-lab/xtb/blob/1c26459e87e3dc718b21fc6d2f061eaf1c93e504/meson.build#L45-L46

But there are other issues that one has to take care of when commenting out this lines, like

https://github.com/grimme-lab/xtb/blob/1c26459e87e3dc718b21fc6d2f061eaf1c93e504/meson.build#L99-L101

The shared linking of the executable than also needs the `dependencies_sha` instead of `dependencies_exe`.

Maybe a new option in `meson_options.txt` (see https://mesonbuild.com/Build-options.html) like

```meson
option('static_executable', type: 'boolean', value: true)
```

would solve this issue.

**Comment by hokru** [comment]
I have made only little progress. I don't really know how to do `meson` things.
This branch/commit https://github.com/hokru/xtb/commit/f8369ce6a96cbf5154fc2ca0ef968abdac7baecd will compile on my mac with intel compiler.
After fixing the `rpath` manually I am stuck at this:

```
manipur:build kruse$ ./xtb --version
dyld: Symbol not found: _mkl_serv_inspector_loaded
  Referenced from: /opt/intel/compilers_and_libraries_2019.3.199/mac/mkl/lib//libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /opt/intel/compilers_and_libraries_2019.3.199/mac/mkl/lib//libmkl_intel_lp64.dylib
Abort trap: 6
```
-----

I dont know why, but a `main()` entry point was needed:
https://github.com/hokru/xtb/commit/951f4c4e98f5b603b86160c1d8e5438918a9e0a8

**Comment by awvwgk** [comment]
Thanks for looking into this.

I have some concerns regarding your changes here:
https://github.com/hokru/xtb/blob/f8369ce6a96cbf5154fc2ca0ef968abdac7baecd/symmetry/symmetry_i.c#L2001
Doing this should result in an unusable `xtb` binary. I compiled it from your fork, but had to revert this line: 
https://github.com/hokru/xtb/blob/f8369ce6a96cbf5154fc2ca0ef968abdac7baecd/meson.build#L334
The `xtb` binary is in fact unusable, since it only contains your additional `main` routine which returns just `0`.

Also I don't understand why you are removed the linking with MKL and the Intel Fortran libraries.

**Comment by hokru** [comment]
I link manually to know and control what is happening while linking. This is just a temporary hack.
Also meson doesn't find my mkl libraries and I don't know how to fix that.

> The xtb binary is in fact unusable, since it only contains your additional main routine which returns just 0.

That would explain my latest issue :-)

**Comment by hokru** [comment]
progress! I got a working binary! I'll update my fork soon-ish.

**Comment by hokru** [comment]
For the record, part of the troubles were that `icc` is used by default for linking the binary instead of `ifort`.

no luck using the `link_language` feature so far.
(https://mesonbuild.com/Release-notes-for-0-51-0.html#new-target-keyword-argument-link_language)

**Comment by awvwgk** [comment]
Cool. Linking with `icc` is usually okay, if one adds the Fortran libraries as dependency.

**Comment by hokru** [comment]
ups, I forgot to update the branch.
I failed at making meson do what is needed, but I will provide the manual instructions.

**Comment by awvwgk** [comment]
@hokru would you mind checking if #40 allows builds on OSX? I don't have a Mac so I can't check.

**Comment by hokru** [comment]
I updated OP. PR 40 helped but I still get meson errors I don't know how to fix.

I provided semi-manual instructions in OP that produce a working binary for me. No idea why I need to link both libxtb versions at this point either.

Perhaps I can bring my mac coming Thursday and we can have a look together.

**Comment by awvwgk** [comment]
@hokru Sounds like a plan. Having an actual Mac around will make this *way* easier to fix. :christmas_tree:
