### ISSUE TITLE
Run xtb on a single core

### ISSUE THREAD

**Issue by gooaah** [grimme-lab/xtb#13]
I am performing crystal structure search using xtb. I need to run many xtb jobs on single cores. However, xtb always uses too many resources and then will be killed by the LSF job scheduler. So how to force xtb running on a single core? Or recompile the code?

**Comment by awvwgk** [comment]
Thanks for your report. To help you with your issue I will need a little more information, like

- what system size you are investigating (hundreds of atoms, thousands)?
- what is your environment setup (`OMP_NUM_THREADS`, `MKL_NUM_THREADS`)?
- how are you calling `xtb` (using `--parallel`)?
- what Hamiltonian are you using (they differ in the cpu-time and memory requirement significantly)?
- what kind of calculations are you performing (MD, optimizations, frequencies)?

**Comment by gooaah** [comment]
> 
> 
> Thanks for your report. To help you with your issue I will need a little more information, like
> 
>     * what system size you are investigating (hundreds of atoms, thousands)?
> 
>     * what is your environment setup (`OMP_NUM_THREADS`, `MKL_NUM_THREADS`)?
> 
>     * how are you calling `xtb` (using `--parallel`)?
> 
>     * what Hamiltonian are you using (they differ in the cpu-time and memory requirement significantly)?
> 
>     * what kind of calculations are you performing (MD, optimizations, frequencies)?

Thanks for your reply.

* The system is molecular crystal containning 168 atoms.

* I have never set these parameters and they have no default values on our cluster. I will set OMP_NUM_THREADS=1 to test.

* I am searching for molecular crystal so I use GFN0_PBC. I called xtb through ase. xtb only performs SCF and the optimization is done by ase.  xtb SCF is valid most of the time. But I need to optimize thousands of structures and some structures lead to a crash.

**Comment by awvwgk** [comment]
Thanks for the clarifications, please check if this fixes your issue. Also set `MKL_NUM_THREADS=1` since the MKL is usually doing the heavy calculations, for more details on the parallel setup refer to the [documentation](https://xtb-docs.readthedocs.io/en/latest/setup.html#parallelisation).

Keep in mind that the GFN0-xTB parametrisation is still preliminary and will change in the near future. But if you run into a crash with a chemical reasonable structure open a new bug report, please.

I will close the issue for now.
