### ISSUE TITLE
Compilation of xtb fails with GCC 5

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/xtb#131]
_Originally posted by @dplacencia in https://github.com/grimme-lab/xtb/pull/58#issuecomment-595474205_

>Hi guys. Thanks for add support for GCC. I'm trying to compile XTB with gcc and gfortran and I got this error:
>
>```
>[8/307] Compiling Fortran object 'xtb@sta/xtb_tbdef_atomlist.f90.o'.
>FAILED: xtb@sta/xtb_tbdef_atomlist.f90.o 
>gfortran -Ixtb@sta -I. -I../xtb-master -I../xtb-master/include -L/opt/apps/easybuild/software/ATLAS/3.10.2-GCC-5.4.0-2.26-LAPACK-3.6.1/lib -L/opt/apps/easybuild/software/Meson/0.51.2-GCCcore-8.3.0-Python-3.7.4/lib -L/opt/apps/easybuild/software/FFTW/3.3.8-gompi-2019a/lib -L/opt/apps/easybuild/software/ScaLAPACK/2.0.2-gompi-2019a-OpenBLAS-0.3.5/lib -L/opt/apps/easybuild/software/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/lib -L/opt/apps/easybuild/software/GCCcore/5.4.0/lib64 -L/opt/apps/easybuild/software/GCCcore/5.4.0/lib -fdiagnostics-color=always -pipe -Wall -O2 -g -fdefault-real-8 -fdefault-double-8 -ffree-line-length-none -fbacktrace -fopenmp -O2 -ftree-vectorize -march=native -fno-math-errno -O2 -ftree-vectorize -march=native -fno-math-errno -D_FILE_OFFSET_BITS=64 -fPIC -Jxtb@sta -o 'xtb@sta/xtb_tbdef_atomlist.f90.o' -c ../xtb-master/xtb/tbdef_atomlist.f90
>../xtb-master/xtb/tbdef_atomlist.f90:20:7:
>
>    use iso_fortran_env, wp => real64
>       1
>Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-real-8
>../xtb-master/xtb/tbdef_atomlist.f90:23:44:
>
>    public :: size, len, assignment(=), write(formatted), read(formatted)
>                                            1
>Error: Syntax error in PUBLIC statement at (1)
>../xtb-master/xtb/tbdef_atomlist.f90:91:18:
>
>    interface write(formatted)
>                  1
>Error: Syntax error: Trailing garbage in INTERFACE statement at (1)
>../xtb-master/xtb/tbdef_atomlist.f90:92:22:
>
>       module procedure :: atomlist_write_formatted
>                      1
>Error: MODULE PROCEDURE at (1) must be in a generic module interface
>../xtb-master/xtb/tbdef_atomlist.f90:93:6:
>
>    end interface write(formatted)
>      1
>Error: Expecting END MODULE statement at (1)
>../xtb-master/xtb/tbdef_atomlist.f90:95:17:
>
>    interface read(formatted)
>                 1
>Error: Syntax error: Trailing garbage in INTERFACE statement at (1)
>../xtb-master/xtb/tbdef_atomlist.f90:96:22:
>
>       module procedure :: atomlist_read_formatted
>                      1
>Error: MODULE PROCEDURE at (1) must be in a generic module interface
>../xtb-master/xtb/tbdef_atomlist.f90:97:6:
>
>    end interface read(formatted)
>      1
>Error: Expecting END MODULE statement at (1)
>../xtb-master/xtb/tbdef_atomlist.f90:29:22:
>
>    type :: tb_atomlist
>                      1
>Warning: Only array FINAL procedures declared for derived type tb_atomlist defined at (1), suggest also scalar one [-Wsurprising]
>[9/307] Dep hack
>ninja: build stopped: subcommand failed.
> (at easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/tools/run.py:529 in parse_cmd_output)
>== 2020-03-05 17:08:27,872 easyblock.py:3109 WARNING build failed (first 300 chars): cmd " ninja -j 8 test" exited with exit code 1 and output:
>```
>
>I hope you can help me. Thanks

**Comment by awvwgk** [comment]
@dplacencia I moved your post here for better reference. Please, don't post off-topic in other threads.

Also, to actually help you with this, I would have to know the version of your GCC compiler, because there is quite a range.

**Comment by dplacencia** [comment]
Thans for you reply. 
GCC 8.2.0
OS Centos 7
I'm traying to compile master branch of XTB.

----- Mensaje original -----
De: Sebastian Ehlert <notifications@github.com>
Para: grimme-lab/xtb <xtb@noreply.github.com>
CC: dplacencia <dplacencia@uclv.cu>, Mention <mention@noreply.github.com>
Enviado: Fri, 06 Mar 2020 03:33:50 -0500 (CST)
Asunto: Re: [grimme-lab/xtb] Compilation of xtb fails with GCC (#131)

@dplacencia I moved your post here for better reference. Please, don't post off-topic in other threads.

Also, to actually help you with this, I would have to know the version of your GCC compiler, because there is quite a range.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/grimme-lab/xtb/issues/131#issuecomment-595660257
-- 
************************************************
Ing. Daniel Placencia Alvarez
HPC Systems Administrator
Universidad Central “Marta Abreu” de Las Villas
dplacencia@uclv.cu  
www.uclv.hpc.cu
HPC UCLV Soporte: soporteuclv@listas.hpc.cu
************************************************

**Comment by awvwgk** [comment]
The CI is using GCC 8.3.0 and I'm developing with the very same version. Can you verify that you are using a GCC 8, because the error message looks very much like a pre-GCC 7 error (look for the actual compiler version in `meson-logs/meson-log.txt`).

Please note that the current master branch is subject to change. We are at 2362cd3 right now.

**Comment by dplacencia** [comment]
that's the problem! I am using EasyBuild to compile XTB and it seems that some of the dependencies that I am loading are overlapping on the compiler that I load by default. The compiler I try to load is GCC 8.3.0 and the one that is actually loading is GCC 5.4.0. I will fix this problem and try the compilation again. Thank you very much for the help. regards

----- Mensaje original -----
De: Sebastian Ehlert <notifications@github.com>
Para: grimme-lab/xtb <xtb@noreply.github.com>
CC: dplacencia <dplacencia@uclv.cu>, Mention <mention@noreply.github.com>
Enviado: Fri, 06 Mar 2020 13:34:25 -0500 (CST)
Asunto: Re: [grimme-lab/xtb] Compilation of xtb fails with GCC (#131)

The CI is using GCC 8.3.0 and I'm developing with the very same version. Can you verify that you are using a GCC 8, because the error message looks very much like a pre-GCC 7 error (look for the actual compiler version in `meson-logs/meson-log.txt`).

Please note that the current master branch is subject to change. We are at 2362cd3 right now.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/grimme-lab/xtb/issues/131#issuecomment-595901885
-- 
************************************************
Ing. Daniel Placencia Alvarez
HPC Systems Administrator
Universidad Central “Marta Abreu” de Las Villas
dplacencia@uclv.cu  
www.uclv.hpc.cu
HPC UCLV Soporte: soporteuclv@listas.hpc.cu
************************************************

**Comment by awvwgk** [comment]
Not sure if it can be fixed for GCC 5, but GCC 8 should work for sure.

This is now the second time I'm hearing about EasyBuild. Can you give me some pointers what it is supposed to do? I thought we are shipping `xtb` already with two full-fledged build system, why is there need for an EasyBuild solution here?

**Comment by dplacencia** [comment]
Dear Sebastian. EasyBuild is a very popular scientific software manager in High Performance Computing (HPC) environments, you can find more information about it in the following link (https://easybuild.readthedocs.io/en/latest/). EasyBuild allows you to handle different versions of the same software and even versions compiled with different compilers in the same environment. The advantage of having versions with different compilers is that, according to their needs, the users can choose between them and even compare the performance of both versions. I am an HPC cluster administrator and several users are asking me for XTB compiled in GCC and I am sure that many researchers in the world who use XTB will appreciate having XTB available on EasyBuild. As you say, a few days ago they added to EasyBuild version 6.2.2 of XTB to compile with intel. I would like to be able to make my contribution also by adding support for GCC, this is my goal. Thank you for your help. I am testing with version 8.3.0 of GCC, you will soon hear about this. regards


----- Mensaje original -----
De: Sebastian Ehlert <notifications@github.com>
Para: grimme-lab/xtb <xtb@noreply.github.com>
CC: dplacencia <dplacencia@uclv.cu>, Mention <mention@noreply.github.com>
Enviado: Fri, 06 Mar 2020 15:05:00 -0500 (CST)
Asunto: Re: [grimme-lab/xtb] Compilation of xtb fails with GCC 5 (#131)

Not sure if it can be fixed for GCC 5, but GCC 8 should work for sure.

This is now the second time I'm hearing about EasyBuild. Can you give me some pointers what it is supposed to do? I thought we are shipping `xtb` already with two full-fledged build system, why is there need for an EasyBuild solution here?

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/grimme-lab/xtb/issues/131#issuecomment-595943466
-- 
************************************************
Ing. Daniel Placencia Alvarez
HPC Systems Administrator
Universidad Central “Marta Abreu” de Las Villas
dplacencia@uclv.cu  
www.uclv.hpc.cu
HPC UCLV Soporte: soporteuclv@listas.hpc.cu
************************************************

**Comment by awvwgk** [comment]
This are very helpful information, thanks. I'll open a new issue for EasyBuild, see #133.

**Comment by tobigithub** [comment]
"slightly" related, compiling xtb with gcc and gfortran-8 (8.3.0) under Ubuntu (18.04) works see [here](https://github.com/tobigithub/quantum-xtb/issues/19).

**Comment by awvwgk** [comment]
@tobigithub Thanks for the report, the CI is running tests with `xtb` on Ubuntu 18.04 with GCC 8.3.0 already (https://travis-ci.com/grimme-lab/xtb).
Currently only GCC 8.3.0 works without patching the source. I was able build it with GCC 7.3.0 with the conda-forge toolchain (see https://github.com/conda-forge/staged-recipes/pull/11067 and https://github.com/conda-forge/xtb-feedstock), but had to patch the OMP and inquire usage. GCC 6 and 5 fail due to derived type IO, because it is not implemented in this GCC toolchains, while GCC 9 failed due to new OMP issues, which I still have to investigate.
So we are indeed pretty limited in the choice of GCC toolchains here.

**Comment by tobigithub** [comment]
@awvwgk I understand why people want to use older versions, our machines still run under Ubuntu 16  and maybe on clusters there is no Intel compiler. Xtb is actually portable as a directory setup, or can be started as Singularity or Docker container, and maybe for ARM CPUs its nice to compile, so for production purposes there is no tweaking needed.

I am sure there are reasons to use gcc6 and 5 (released 2015) but speed-wise I would go with the static compiled INTEL standalone files. But yes compiling xtb is needed for all the older CPUs, the repositories etc, plus its nice to do and of course if CentOS, Ubuntu, Debian, Mint and other distros are covered even better.

**Comment by awvwgk** [comment]
Let's put it that way, there can be always done more for distributing software, but with `xtb` I strive for solutions I can support in some way without eating away my already limited time. If it is not native available on OpenSuse due to missing rpm packages, this is a pity but offers the unique opportunity to contribute to an open source project.

@tobigithub If you want to provide a Singularity or Docker container or are a package maintainer for CentOS, Ubuntu, Debian or Mint and want to package `xtb`, then I'm more than happy to help you get this running. Just open a new feature request and we can discuss the details.

**Comment by tobigithub** [comment]
@awvwgk I am just happily compiling, (not a distro maintainer) however I may work on a docker or singularity solution, I will add that to my to-do list.

**Comment by awvwgk** [comment]
Closing this, since GCC 5 support is not really desirable as we are moving to modern features already.
