### ISSUE TITLE
6.3.1 still slower than 6.2.3 (>2 times)

### ISSUE THREAD

**Issue by Dnasiul** [grimme-lab/xtb#262]
Hi XTB developers. Here again with the timing issue.

**Describe the bug**
6.3.1 still slower than 6.2.3 (>2 times)

**To Reproduce**
Steps to reproduce the behaviour:

1. Included input xyz file
2. xtb graphene.xyz --gfn 2 --opt
3. Included output from both versions

**Expected behaviour**

Same timing.

**Additional context**

NCORES=4

**Note**

6.3.1 doesn't report the number of omp threads in the Calculation Setup.

[graphene_xyz.txt](https://github.com/grimme-lab/xtb/files/4782190/graphene_xyz.txt)
[output_6_2_3_NCORES_4.txt](https://github.com/grimme-lab/xtb/files/4782204/output_6_2_3_NCORES_4.txt)
[output_6_3_1_NCORES_4.txt](https://github.com/grimme-lab/xtb/files/4782206/output_6_3_1_NCORES_4.txt)

**Comment by awvwgk** [comment]
Man, I thought I had put up the correct binaries for the release. This is the wrong commit hash in the header, let's see if I can get the upload right this time.

**Comment by awvwgk** [comment]
Just uploaded the correct tar-ball: https://github.com/grimme-lab/xtb/releases/download/v6.3.1/xtb-200615.tar.xz

**Comment by Dnasiul** [comment]
Now it is significantly better, just ~1.4 times slower.

Thanks.

**Comment by awvwgk** [comment]
The remaining 0.4 are probably due to different number of SCC cycles, if you reduce the numerical thresholds in 6.3.1 with `--acc 10` you will probably find another speed-up. Once I unified the scale of numerical accuracy value for the FF and the xTB methods we can go back to the full-automatic handling of numerical accuracies.

For now I will close this issue and hope I'm not going to break the parallelisation again.
