### ISSUE TITLE
Add warning and option for adding explicit hydrogens

### ISSUE THREAD

**Issue by tobigithub** [grimme-lab/xtb#28]
**Is your feature request related to a problem? Please describe.**

Many semiempirical tools warn if explicit hydrogen atoms are missing and add them automatically if needed (Ampac, Spartan, Gaussian etc). Currently xtb calculates any molecule with and without explicit hydrogens added. This is true for coord (tmol) and mol/sdf input. While we can expect that the user takes care of it, it would be a friendly and helpful feature nevertheless. Plus new users who are not aware of the fact, may just end up with false results.

See also case (mod/sdf reader) : https://github.com/grimme-lab/xtb/issues/26

> (R3) Input check, add information if explicit hydrogens are required in the mol/sdf file (xtb does not care about molecules to be chemically valid, they currently can have hydrogens attached or not, xtb will perform an optimization either way) give potential warning if hydrogens are missing.

> Same as for 1., we need hydrogen atoms for the calculation, unless we preprocess the structure explicitly such input is not suitable for GFN-xTB calculations.

**Example 1 (xtb benzene no hydrogen)**:
Still gives Energy and HOMO-LUMO, even with hydrogens missing.
````
$ cat benzene-nohydrogen.tmol
$coord
   -3.75412991991227      4.38529844566012      0.00000000000000      c
   -5.10433923622019      3.60559744648777      0.00000000000000      c
   -5.10433923622019      2.04657339336806      0.00000000000000      c
   -3.75412991991227      1.26706136680820      0.00000000000000      c
   -2.40392060360435      2.04657339336806      0.00000000000000      c
   -2.40392060360435      3.60559744648777      0.00000000000000      c
$end
````

````
xtb benzene-nohydrogen.tmol --opt extreme

number of atoms            :                     6
number of electrons        :                    24
charge                     :                     0
spin                       :                   0.0

optimized geometry written to: xtbopt.coord
           -------------------------------------------------
          | TOTAL ENERGY              -12.407726270224 Eh   |
          | GRADIENT NORM               0.000025716823 Eh/α |
          | HOMO-LUMO GAP               0.509781249335 eV   |
           -------------------------------------------------
------------------------------------------------------------------------
 * finished run on 2019/10/21 at 15:23:29.476
------------------------------------------------------------------------
 total:
 * wall-time:     0 d,  0 h,  0 min,  0.206 sec
 *  cpu-time:     0 d,  0 h,  0 min, 14.602 sec
 * ratio c/w:    70.826 speedup
 SCF:
 * wall-time:     0 d,  0 h,  0 min,  0.011 sec
 *  cpu-time:     0 d,  0 h,  0 min,  0.806 sec
 * ratio c/w:    73.660 speedup
 ANC optimizer:
 * wall-time:     0 d,  0 h,  0 min,  0.111 sec
 *  cpu-time:     0 d,  0 h,  0 min,  9.104 sec
 * ratio c/w:    82.373 speedup

normal termination of xtb
````

**Example 2 (xtb benzene with explicit hydrogen)**:
Gives Energy and HOMO-LUMO, with explicit hydrogens added.

````
$ cat benzene-withhydrogen.tmol
$coord
   -3.75412991991227      4.38529844566012      0.00000000000000      c
   -5.10433923622019      3.60559744648777      0.00000000000000      c
   -5.10433923622019      2.04657339336806      0.00000000000000      c
   -3.75412991991227      1.26706136680820      0.00000000000000      c
   -2.40392060360435      2.04657339336806      0.00000000000000      c
   -2.40392060360435      3.60559744648777      0.00000000000000      c
   -3.75412991991227      6.33549580665351      0.00000000000000      h
   -6.79330228572693      4.58062235090121      0.00000000000000      h
   -6.79325111200677      1.07145984990115      0.00000000000000      h
   -3.75412991991227     -0.68313599418518      0.00000000000000      h
   -0.71500872781776      1.07145984990115      0.00000000000000      h
   -0.71495755409760      4.58062235090121      0.00000000000000      h
$end
````
````
xtb benzene-withhydrogen.tmol --opt extreme

number of atoms            :                    12
number of electrons        :                    30
charge                     :                     0
spin                       :                   0.0


optimized geometry written to: xtbopt.coord

           -------------------------------------------------
          | TOTAL ENERGY              -15.879640657257 Eh   |
          | GRADIENT NORM               0.000026294465 Eh/α |
          | HOMO-LUMO GAP               4.934269154112 eV   |
           -------------------------------------------------
------------------------------------------------------------------------
 * finished run on 2019/10/21 at 15:26:31.895
------------------------------------------------------------------------
 total:
 * wall-time:     0 d,  0 h,  0 min,  0.161 sec
 *  cpu-time:     0 d,  0 h,  0 min, 11.539 sec
 * ratio c/w:    71.603 speedup
 SCF:
 * wall-time:     0 d,  0 h,  0 min,  0.015 sec
 *  cpu-time:     0 d,  0 h,  0 min,  1.118 sec
 * ratio c/w:    76.941 speedup
 ANC optimizer:
 * wall-time:     0 d,  0 h,  0 min,  0.106 sec
 *  cpu-time:     0 d,  0 h,  0 min,  8.564 sec
 * ratio c/w:    81.042 speedup

normal termination of xtb
````

**Describe the solution you'd like**
A simple warning that the solution is not correct in case of explicit hydrogens missing, plus a command line switch to automatically add missing hydrogens.

**Describe alternatives you've considered**
Use obabel and molconvert to add explicit hydrogens. 

**If possible state how you can assist in providing data or code to to implement the feature**
I can test molecules, including charged and radical entities. 

**Additional context**

- openbabel add explicit hydrogens (from help file)
PROMPT> babel -isdf  'mymols.sdf' -osmi 'outputfile.smi' -h
- molconvert add explicit hydrogens (+H after target format)
molconvert sdf:+H "CCC"

**Comment by awvwgk** [comment]
In case of PDB or molfile/SDF input this is useful, since a kind of meta-information about hydrogen atoms is present in the file format (*e.g.* for a PDB file it is extremely unlikely to encounter a valid input without any hydrogen atoms). For molfile/SDF input it is more difficult, any assumption on the topology or valency of an atom without performing a calculation is out-of-scope for `xtb`. The hydrogen atom query field can be used to determine if explicit hydrogen atoms are missing and to reject input, but it is not required to be present if no explicit hydrogen atoms are given. A more sophisticated scheme would use the formal charges, topology information and bond orders to check for missing hydrogen atoms, which in my opinion is actually the responsibility of the provider. 

For Turbomole coordinates and xyz input this check has to be performed by the provider of the input geometry, `xtb` should not perform any checks for topology or valency here.

**Comment by sozenoid** [comment]
Related to this topic, xtb will refuse to process a molecule supplied in an .pdb format without any hydrogen even when the molecule is valid. An example is hexafluorobenzene which xtb will accept as .sdf format but reject as .pdb. I think adding a warning in an absence of hydrogens is fine but rejecting the input seems a bit too conservative. 

>    * xtb version 6.3.3 (5b13467) compiled by 'ehlert@majestix' on 2020-09-17

> ########################################################################
[ERROR] Program stopped due to fatal error
-2- reading geometry input 'testmol2.pdb' failed
-1- io_reader_readMolecule: You get no calculation today, please add hydrogen atoms first
########################################################################
