### ISSUE TITLE
[Q] For what macOS version/s is the xtb Mac binary available?

### ISSUE THREAD

**Issue by alanarnold** [grimme-lab/xtb#295]
Nice to hear that a xtb Mac binary is available for conda. I've been successfully using xtb 6.3.1 and crest on Ubuntu 18.04 running under Parallels Desktop 15 on my Macbook with macOS Catalina, and on an old 12-core MacPro with High Sierra, but a native binary would be simpler to manage. 

 ##For what macOS version/s has the xtb binary been made?

**Comment by awvwgk** [comment]
First, there is no OSX version of `xtb` available other than conda-forge package. Main reason for this is that I'm packaging the `xtb` binary distribution at our cluster in Bonn and don't have (physical) access to a device running OSX.

To be clear, any packaging of a binary distribution for OSX will therefore be based on a CI solution for now. For the Unix binary distribution we face the issue of linking and dependencies, this is solved in our case by compiling on a fairly old OpenSuse machine and statically linking against the oldest compatible Intel Parallel Studio version.

From my limited knowledge about OSX, we face an issue with linking the program statically as it is not possible, so it is not clear to me how compatible an OSX binary uploaded from the CI server will be. Since there are far less OSX versions out there than Unix distros this might be only a minor issue.

The other point is distribution, I would prefer a proper package manager, to my knowledge there are two major ones for OSX:
- conda
- homebrew

We already distribute via conda-forge but could probably setup a tap with homebrew formulas as well.

**Comment by alanarnold** [comment]
Thanks for this. I'll try the conda-forge package.

**Comment by aronwalsh** [comment]
@alanarnold did you have success with `conda install xtb`? On MacOS Catalina, the resulting `xtb` gives a segmentation fault for me. I tried a clean environment and get the same result sadly.

**Comment by awvwgk** [comment]
Please keep in mind that even an installation with conda requires to follow the general setup steps: https://xtb-docs.readthedocs.io/en/latest/setup.html
Especially a too low (or default) OMP and system stacksize will cause stackoverflows and segmentation faults.

**Comment by aronwalsh** [comment]
I was being silly @awvwgk. The seg fault was for running `xtb` with no input. `xtb --version` works, as do simple examples. Thanks for your efforts in supporting Mac!

**Comment by alanarnold** [comment]
@aronwalsh Thanks for the reminder :) The conda install proceeded nicely on macos Catalina 10.15.5 for me (just upgrade to 10.15.6) and a few small xtb runs have completed OK.

Surprisingly (?) the run-times of the few geometry-optimisation/hessian jobs that I've run are a bit slower in the conda version than identical jobs run on an Ubuntu18.04 VM under Parallels Desktop 15. I naively expected that the VM might have added some significant overheads but that doesn't seem to be the case.

Both implementations use the following in ~/.bashrc

# setup some xtb environment parameters
export MKL_NUM_THREADS=2
#distribute the number of threads in the OMP section
export OMP_THREAD_LIMIT=2
export OMP_NUM_THREADS=${OMP_THREAD_LIMIT},1
# deactivate nested OMP constructs
export OMP_MAX_ACTIVE_LEVELS=1
export OMP_STACKSIZE=1G
ulimit -s unlimited

The only other minor issue I've experienced in the conda version is the non-fatal floating-point exception warning message shown below:

Alans-MacBook-Air:xtb alanarnold$ xtb Q4.xyz --ohess extreme > Q4__opt_extreme_hess_conda-6.3.1.out &
[1] 20685
Alans-MacBook-Air:xtb alanarnold$ normal termination of xtb
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

Not a big deal but as I've just upgraded to xtb 6.3.2 on Ubuntu on the laptop, I'll stick with that for a while.

**Comment by awvwgk** [comment]
The precompiled binary for Linux is produced with the Intel Compiler, which seem to generally produce faster binaries than GCC. The main performance difference is usually the linear algebra backend, which is MKL with the precompiled one, but might be OpenBLAS with the conda-forge distribution (but can be changed to MKL as well).

To gain the same performance on OSX as with the precompiled Linux binary, one would have to install the Intel compilers and the MKL and compile from source. The issue with this is that the resulting binary might not be portable due to static linking issues on OSX.

**Comment by awvwgk** [comment]
I'll close this issue for now, we currently don't have Mac's around to compile Intel versions of `xtb` and probably won't buy an OSX system for this purpose. But since the Intel oneAPI release compiling `xtb` on your own Mac should be straight forward enough now.
