### ISSUE TITLE
param_gfn0-xtb.txt not findable in conda install 

### ISSUE THREAD

**Issue by jhjensen2** [grimme-lab/xtb#384]
`conda install -q -y -c conda-forge xtb` works fine (i.e. GFN1 and GNF2) except that gfn0 calculations fail:

[ERROR] Program stopped due to fatal error
-3- Could not setup parameterisation
-2- main_setup_newCalculator: Could not construct new calculator
-1- main_setup_newXTBCalculator: Parameter file param_gfn0-xtb.txt not found!

The file is there (in /usr/local/share/xtb) together with the other param files

[link to notebook](https://colab.research.google.com/drive/1rDgB668Gdde22MD-42-929qVIhC_oE-L?usp=sharing)

**Comment by awvwgk** [comment]
The file should be installed correctly even with conda, the issue is that the `XTBPATH` variable is not setup correctly, which I currently cannot do in a conda package. `xtb` is currently not searching beyond the `XTBPATH` for parameter files.

```sh
XTBPATH=/usr/local/share/xtb xtb ...
```

Setting a default search paths for `/usr/share/xtb:/usr/share/local/xtb` in `xtb` would solve this issue, but doesn't solve the issue if `conda` is installed in a local prefix like `/home/user/miniforge3`.

**Comment by ekwan** [comment]
If loading from conda, set XTBHOME to .../miniconda3/envs/whatever/share/xtb.
