### ISSUE TITLE
Segmentation fault on start for gfortran v8.3.0

### ISSUE THREAD

**Issue by clavigne** [grimme-lab/xtb#432]
xtb segfaults on start when built with gfortran v.8.3.0 but not with v9.3.0. [Here is the output of a debug build of the breaking commit below.](https://github.com/grimme-lab/xtb/files/5905602/xtb.txt)

Specifically, the crash occurs when open_file() is executed the second time in newXTBCalculator at [src/main/setup.F90](https://github.com/grimme-lab/xtb/blob/d4b70c2b361067f291e81c3df1d1c31c28d01cb4/src/main/setup.f90#L200). This appears to be a bug in gfortran, as later version of gfortran works fine.

I did a git-bisect and the error was "introduced" in commit 7be4776e7f6c2449e1580600968e1d354fc7a4cf  . However the error was already latent, it just didn't crop up when running xtb because pcem_file was not allocated before newXTBCalculator is called. 

Hotfixes:
- Moving init_pcem to after newXTBCalculator "solves" the problem, but I think it's a bad idea, because the error will pop up when pcem_file is allocated anyway.
- Moving the open_file call to a new subroutine and calling this subroutine from newXTBCalculator also works.
- Switching to newer gfortran resolves the issue.

I believe the problem is a bug in gfortran's treatment of character(len=*) and character(len=:) arrays, that crops up in this weird spot. I can't find exactly the issue in the 1000s of bugfixes that gfortran has done since v8.3. So I think the solution that makes the most sense is **enforcing gfortran version to 9 or higher in CMake / meson.**

Then the current code, which looks correct and elegant to me, can be kept but potential users that are building xtb will be informed that the problem is known.

**Comment by awvwgk** [comment]
In fact `xtb` works fine with GCC 7.5, so I would assume that this bug is fixed with GCC 8.4 as well. Keeping a list of supported compiler versions is tedious work, unless enforces by continuous testing this information tends to be outdated rather quickly. Maintaining such a list in the build files is not an option for me, because it requires to be very specific on compiler versions, even including patch version to some extend, maybe even operation systems and platform architectures.

From a recent discussion at @fortran-lang's stdlib we arrived at the strategy to have a list of supported compilers, which are continuously tested, while failing compilers + platform + architecture are listed more explicitly instead, preferably including a link to the respective issue. This is still quite taxing to maintain even with a testing matrix of 12 GCC versions as used in stdlib.

With the limited testing of 4 GCC versions I'm doing on `xtb` right now, I'm not sure if this can work for `xtb` in the long run.

One possibility would be to make this a community resource and maybe create a GitHub wiki with a dedicated page to allow users to report working and failing compiler versions for certain xtb versions.

**Comment by clavigne** [comment]
mmm that's even nastier than I thought! I guess I should get off slow-moving Debian, I didn't even know there was another minor version of GCC8. I should have done the compiling with conda.

You are right, there isn't any point in trying to exhaustively list working and non-working version of just GCC, let alone GCC + PGI + ifort. It's way too much work. I'm already surprised you already do four versions.

One final possibility to think about would be to deprecate gfortran < 9. The conda version is gfortran 9.3.0, and that's readily available even on shared machines (and what I'll make sure to use in the future).

**Comment by awvwgk** [comment]
Currently I don't see a reason to deprecate working GCC versions. I know that GCC 6 and earlier are not working since they do not implement the Fortran 2003 standard completely, which is required for the core functionality of `xtb`.

As a little exercise I collected all the compilers I tested for this release and there is indeed a gap for GCC 8 in my testing:

Compiler | Version | Platform | Architecture | ``xtb``
--- | --- | --- | --- | ---
 GCC |       10.2 |       Manjaro Linux |           x86_64 |        6.4.0
 GCC |       10.2 |       Windows Server 2019 |  x86_64 |        6.4.0, latest
 GCC |       9.3 |  Ubuntu 18.04 |  x86_64 |        6.4.0, latest
 GCC |       9.3 |  Centos 7 |  ppc64le, aarch64 |       6.4.0
 GCC |       9.3 | Centos 6 |  x86_64 |        6.4.0
 GCC |       9.3 |        MacOS 10.15.7 |        x86_64 |        6.4.0, latest
 GCC |       7.5 |        Ubuntu 18.04 |         x86_64 |        6.4.0, latest
 Intel |     2021.1 |      Ubuntu 20.04 |         x86_64 |        6.4.0, latest
 Intel |     18.0.2 |     OpenSuse 42.1 |             x86_64 |        6.4.0
 NVHPC |      20.11 |      Manjaro Linux |        x86_64 |        6.4.0
 NVHPC |     20.9 |       Centos 8 |             x86_64 + cc70 |        6.4.0
 NVHPC |     20.7 |       OpenSuse 42.1 |             x86_64 + cc35 |        6.4.0

Toolchains I found not working

Compiler | Version | Platform | Architecture | ``xtb`` | Issue
--- | --- | --- | --- | --- | ---
 Intel |     17.0.7 |     OpenSuse 42.1 |      x86_64 |        6.4.0 |  ICE in ``src/hessian.F90``
 NAG | 7.0 | Centos 8 | x86_64 | 6.4.0 | missing build system support

**Comment by clavigne** [comment]
Anyway, thanks for your help and the awesome job you all have been doing. It's a great piece of software.
