### ISSUE TITLE
hess calculation seg fault

### ISSUE THREAD

**Issue by ucb-mgcf** [grimme-lab/xtb#458]
**Describe the bug**
I'm getting a SIGSEGV seg fault for a --hess calculation.  The structure was successfully optimized in xtb.

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input: 
[start.txt](https://github.com/grimme-lab/xtb/files/6167717/start.txt)

2. start `xtb` with xtb start.xyz --ohess extreme > output.  Although I've also had the same result when using xtb start.xyz --chrg 0 --uhf 0 --hess --grad > xtbout
3. output is same for --verbose 
4. last printout before seg fault is for the time estimates for hessian calculation

Please provide all input and output file such that we confirm your report.

**Expected behaviour**
hess calculation should run to completion

**Additional context**
I'm using binary release, xtb version 6.4.0 (d4b70c2).  I saw a couple of earlier related bugs from last year, but these were fixed before this version.

**Comment by awvwgk** [comment]
Can confirm that it segfaults with 6.4.0 and latest head (9c8c9fdf7fc760ef3a1a1161954ed8db39bbc47e), not sure what is causing it but it seems to be related to the parallelization on the displacements in the hessian. Inverting the distribution of the cores in the hessian `OMP_NUM_THREADS=1,32` instead of `OMP_NUM_THREADS=32,1` runs without problems, putting in more than one core on the hessian parallelization triggers the bug.

**Comment by ucb-mgcf** [comment]
Thanks for the reply.  I've tried this fix and it works for me.  Would you suggest using this number-of-threads inversion generally, or only when this error occurs?

**Comment by awvwgk** [comment]
Not really a fix but more a diagnostic here, using the threads to parallelize over the displacements will be more efficient than using them to in the electronic structure method while evaluating the displacements sequentially.

There are several issues with the numerical differentiation I have to look into, will do so soon.
