### ISSUE TITLE
incorrect gradient for GFN1 and GFN2

### ISSUE THREAD

**Issue by hegelyb** [grimme-lab/xtb#492]
**Describe the bug**
The numerical gradient with respect to the coordinates of atom 1 and 2 differs from the analytical gradient in the case of GFN1-xTB and GFN2-xTB with about 10^(-2) au. Starting from atom 3, everything is fine and this behavior is not experienced if the GFN0-xTB or GFN-FF is used.

**To Reproduce**
I'm using the precompiled binaries (xtb-6.4.0) 
* xtb version 6.4.0 (d4b70c2) compiled by 'ehlert@majestix' on 2021-02-01

1. Run the xtb program: 
xtb ph.coord --input ph.xtbinp --grad --namespace ph --verbose --etemp 300 --grad > ph.out
xtb mh.coord --input mh.xtbinp --grad --namespace mh --verbose --etemp 300 --grad > mh.out
xtb ph.coord --input ph.xtbinp --grad --namespace ph --verbose --etemp 300 --grad > zh.out
where the three geometries only differ in the x coordinate of the first atom (oxygen of the ethanol). Note that the test molecule does not have symmetry.
2. Calculate the force on atom 1 using a two-point numerical differentiation:
foce = [ energy(ph.out) - energy(mh.out) ] / ( 2 * h * [angtobohr] ) ; where h is 0.001 Angstrom.
force = [ -11.387356034674 - (-11.387405263416) ] / (2*0.001/0.52917721067) = 0.0130253636590041 au 
3. Compare the x component of the force acting on atom 1 (from zh.gradient) with the above force:
-0.0068798707973265 - (0.0130253636590041) = 2*10^(-3) au

I attached all the necessary input and output files for the above calculation.

**Expected behaviour**
I expect that the numerical and analytical gradient match within 10^(-6) au regardless of the inspected force component.
[ethanol_gfn2_mh.tar.gz](https://github.com/grimme-lab/xtb/files/6695959/ethanol_gfn2_mh.tar.gz)
[ethanol_gfn2_ph.tar.gz](https://github.com/grimme-lab/xtb/files/6695960/ethanol_gfn2_ph.tar.gz)
[ethanol_gfn2_zh.tar.gz](https://github.com/grimme-lab/xtb/files/6695961/ethanol_gfn2_zh.tar.gz)

Please confirm that you can reproduce my findings.
Best regards,
Bence

**Comment by awvwgk** [comment]
Sorry, but this very unlikely. Please be careful which such generalized claims. `xtb` provides a numerical gradient check which you can employ in case of doubt, just set the `debug` variable here on `.true.` and you can verify the implementation:

https://github.com/grimme-lab/xtb/blob/afa7bdffd36dee5f58b6f658004a3bac3567aabc/src/prog/main.F90#L161

(if you don't want to built a version locally, fork the `xtb` repository, enable workflows on the actions tab of your fork, edit the file on a branch and commit the change. The CI will automatically create a new pre-release tag on your fork where you can download a statically linked version)

Taking your `mh.coord` input I can produce something that looks like an erroneous analytical gradient:

```
❯ ./_build_intel/xtb --namespace mh mh.coord  --acc 1.0 --norestart
...
difference gradient
  2.907332557686160E-007  2.851839099802912E-003 -2.222607725791206E-007
  9.579657432004680E-008 -1.279403294513575E-003  1.262405850185194E-007
 -3.547763256445471E-007 -1.572338187325920E-003  1.085945934703458E-007
 -2.320815009008298E-008 -3.601516184283463E-008 -9.781014435883417E-010
  5.311668797511326E-009 -4.939086145627769E-008 -3.039449586982046E-009
  2.394354283201047E-009 -7.808500807977379E-004  5.142305031791139E-008
  2.613453532513028E-008  7.808099768792092E-004 -1.116075367237415E-008
 -1.451569934596882E-008 -2.241167219776269E-008 -4.998719806137419E-008
 -2.715967062724310E-008  4.746147965644428E-008  2.145042847338796E-009
```

There is good reason to doubt the accuracy of a numerical gradient calculated with a naive approach as used above. A rotation of the molecule, *e.g.* into its principal axes of inertia (other rotations work as well, but this one is the easiest because I already have implemented the flag), will completely remove the spurious errors from the numerical gradient.

```
❯ ./_build_intel/xtb --namespace mh mh.coord  --acc 1.0 --cma --norestart
...
difference gradient
 -2.673426866667793E-007  5.958331811446727E-008 -1.451784067381737E-007
  4.788767188346199E-009  1.368921696614719E-007  5.371963415399215E-008
  1.538243851843812E-007 -1.879547075409049E-007  1.484614693121437E-007
  4.721321186925646E-008 -2.004689914937574E-009 -1.631542497675456E-008
  2.831692709221595E-008 -2.558268046015666E-008 -3.983410886906902E-008
  4.192889880433315E-008  2.681621884964569E-008 -1.121483069572386E-008
  1.293915018554283E-008  1.327037571323408E-008  1.560757250702402E-008
 -2.273198762645784E-008  1.365957673360452E-009  8.165598324241796E-009
  1.751556078996575E-010 -2.229714429627730E-008 -1.385559220959051E-008
```

It is important to realize that a naive Cartesian displacement for calculation of numerical differences can fail, quite easily actually. There are certainly more sophisticated methods for differentiation available, which actually provide more stable estimates for the first and second derivatives.

**Comment by hegelyb** [comment]
Thank you for the quick response. Unfortunately, I still can't see clearly why the force calculation is affected by these rotations as the referred code uses the same central difference method with a smaller step size. I guess that the numerical noise can heavily depend on the chosen coordinate system. Either way, thanks again for your effort and time.
