### ISSUE TITLE
referensing issue #503

### ISSUE THREAD

**Issue by lxsep** [grimme-lab/xtb#507]
We have tried with gnf 1 and it converges. Is it possible that the gbsa parameters are not correctly input for gnf 2? or the question should be do both Hamiltonians use the same gbsa parameters? Also we can share the files with you if you provide us an email.

**Comment by awvwgk** [comment]
Thanks for checking. Sometimes certain combinations just don't work for a specific system, changing the Hamiltonian and/or the solvation model can help in this cases.

I moved the issue to the discussion board (see https://github.com/grimme-lab/xtb/discussions/505), let's continue this thread there. Apparently the issues now get closed and locked rather than just transferred.
