### ISSUE TITLE
Is there any plans to release xtb on pypi?

### ISSUE THREAD

**Issue by sunqm** [grimme-lab/xtb#65]
Hi, I'm wondering whether you plan to release xtb on pypi. It would be convenient for a quick start with pip release.

**Comment by awvwgk** [comment]
Not right now, but I hope we are getting there. The are some issues with compiling (see #11, #58) that have to be solved first, also I am not sure if PyPI is the right platform for `xtb`, since it is not strictly a Python project.

I am looking right now into `conda` (https://github.com/dftd4/dftd4/issues/21) for another project, which might be a way to distribute `xtb` as well.

**Comment by dgasmith** [comment]
Please do reach out if you would like help with getting either dftd4 or xtb on conda. Both would be super useful and we use xib a _ton_ in various CI scripts and workflows.

**Comment by awvwgk** [comment]
@dgasmith, you and @loriab helped me a lot in the last months, so many thanks for the offer.

Right now I am the bottleneck regarding further progress in integration and deployment and I will not be able to pick this up too soon, since I have a whole lot of projects to finish first.

**Comment by aozalevsky** [comment]
@awvwgk if you need further help or testing with conda i'd be glad to help.

**Comment by awvwgk** [comment]
@aozalevsky Thanks, this would be really helpful. Right now this is stale, my failed attempt for a conda-forge recipe can be found here: https://github.com/conda-forge/staged-recipes/pull/10563.

So far I have no idea why it failed and not the time to debug it on the CI server, while the recipe works fine with conda-build on my Arch Linux machine.

**Comment by dgasmith** [comment]
Do you still support CMake? Stepping into Meson world is rough as support is still quite weak for it in general.

**Comment by awvwgk** [comment]
Yes, we have CMake support now, thanks to @nabbelbabbel. I'm trying not to break the CMake build system (currently I'm again fighting with CMake, this time to make it find and link `rotl32`, which meson does without problems, but who needs hash functions anyway).

While we officially support CMake, I would prefer to see the conda-forge build with meson, because it already worked for `dftd4` and this is the build system I going to use for shipping production binaries.

**Comment by dgasmith** [comment]
Fair enough, I will probably stay out of the c-f debugging in this case. We have tons of use cases for this if it can go up on conda so best wishes in getting this up!

**Comment by awvwgk** [comment]
I'll push a 6.2.3 release soon and will give `xtb` on conda-forge one last try.

**Comment by ekwan** [comment]
I tried the conda route and it just hung there trying to solve the environment forever.  A friend of mine did get it to work, though.  I am happy to use any reliable method...

**Comment by awvwgk** [comment]
After I found that kitware is able to use PyPI to distribute `cmake` (https://pypi.org/project/cmake/) and `ninja` (https://pypi.org/project/ninja/) there, I might give `xtb` on PyPI another thought.

@dgasmith @sunqm Do you have experience distributing non-Python packages on PyPI?

**Comment by dgasmith** [comment]
It can be simple based on your dependancies, pyscf for example is on PyPI. Reading something like `Numpy` and `pyscf`'s `setup.py` should help, here is the Gau2Grid `setup.py` for use with [CMake](https://github.com/dgasmith/gau2grid/blob/master/setup.py). I wouldn't say its the greatest, but it works.

**Comment by awvwgk** [comment]
Finally, I decided to not distribute `xtb` over PyPI.

Possibly this could be something worth trying for the new Python API of `xtb` at https://github.com/grimme-lab/xtb-python.
