### ISSUE TITLE
Update binary

### ISSUE THREAD

**Issue by arosen93** [grimme-lab/xtb#69]
Would it be possible to build a new xTB binary as a result of the bugfix in https://github.com/grimme-lab/xtb/commit/7ff4d96f5fa3baba4a20ee092c7e70996139f7ca? This is a pretty important bugfix, and unfortunately I am having some trouble compiling xTB from source (trying to sort this out).

**Comment by awvwgk** [comment]
We need to finalize the next release first. Having bleeding edge releases for every commit on the master branch is not really possible without having more automatization.

The fix is successfully implemented on the master branch which should be sufficient until I can setup the next release. You can of course open an issue regarding the build problems and we can try to figure this out.

**Comment by awvwgk** [comment]
It's done.
