### ISSUE TITLE
The protonation energy in water (ALPB/cosmo)

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/xtb#715]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/crest-lab/crest/issues/10 but I wonder if there is any update on this matter.
I'm interested in exploring if GFN2-xTB could be used for pKa calculations. I could get the protonation energy of a small molecule in implicit solvent via two simple calculations but to get the pKa, I will need the protonation energy in water as well. 

**Describe the solution you'd like**
It will be nice if xTB could publish the recommended protonation energy in water for GFN2-xTB with ALPB or cosmo solvation model.

**Comment by MtoLStoN** [comment]
Acid dissociation constants are highly susceptible to slight differences in energy. To calculate accurate values for pKa a rigorous conformational screening is necessary as well as very accurate solvent phase energies (from the purely electronic energy to solvation models). After that, you will still need a method specific fit. Even if you have all of these right, you can still expect errors in the range of up top 1 log unit (see [this](https://pubs.acs.org/doi/full/10.1021/acs.jpca.1c03463) nice paper of P. Pracht). 

So, while from a technical point of view, something like that would be possible, we never really explored this, because the inherent error of our solvation model and the GFN methods would probably lead to results that are orders of magnitude away from reality (on a nonlogarithmic scale).

**Comment by xiki-tempula** [comment]
Thanks. I just need a crude estimate and I could accept 2~3 pKa units of error. I will read the cited paper.

**Comment by MtoLStoN** [comment]
If you are only looking for a crude estimate, you might try the approach published in the paper ([Additional Computational Details](https://pubs.acs.org/doi/suppl/10.1021/acs.jpca.1c03463/suppl_file/jp1c03463_si_002.pdf)).

**Comment by xiki-tempula** [comment]
Thanks.
