### ISSUE TITLE
Could not read topology file

### ISSUE THREAD

**Issue by gnarw** [grimme-lab/xtb#755]
**Describe the bug**
Output file from a --gfnff geometry optimisation run ends with
warning: could not read topology file

Also the slurm output file ends with this warning
"Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
normal termination of xtb"

**To Reproduce**
xtb --gfnff caffeine.xyz  --gbsa water --opt --verbose 

1. happens with input (xtbJob.txt)
the bash file contains these settings
export OMP_NUM_THREADS=24
export MKL_NUM_THREADS=24
export OMP_STACKSIZE=4G
export OMP_MAX_ACTIVE_LEVELS=1
ulimit -s unlimited

3. run `xtb` with your options and the `--verbose` flag
4. output showing the error
"[WARNING] Runtime exception occurred
-1- gfnff_setup: Could not read topology file."

The complete output file is attached (xtb_gfnff_output.txt)

**Expected behaviour**
I expected an optimised structure and no error or warnings

**Additional context**
I never saw these warnings when using xtb version 6.3.3

Could you please comment on these warnings/errors
The run seems to be working ok. Optimisation converges and it outputs xtbopt.xyz
But it would be nice to know if these warnings could be ignored.

[caffeine.txt](https://github.com/grimme-lab/xtb/files/10425612/caffeine.txt)
[xtb_gfnff_output.txt](https://github.com/grimme-lab/xtb/files/10425613/xtb_gfnff_output.txt)
[xtbJob.txt](https://github.com/grimme-lab/xtb/files/10425614/xtbJob.txt)

**Comment by Thomas3R** [comment]
Hello,

Yes, you can safely ignore these warnings. 

The warning about the topology file is simply to remind you that you did not provide a gfnff_topo file.
Since a topology file is created during the first run, you can simply run the same command again and the warning should not appear anymore.
The other warning arises when denormal numbers occur during the execution of the code (numbers near but unequal zero, that can not be represented with the given precision of the variable).
