### ISSUE TITLE
xtb thermo submodule unable to read hessian file from DFTB+

### ISSUE THREAD

**Issue by ankur56** [grimme-lab/xtb#845]
**Describe the bug**

I am trying to compute thermochemical properties using the thermo submodule; however, the program is not able to read the `hessian.out` file from DFTB+.

My `xtb` command is as follows,

`xtb thermo --sthr 100 --temp 298.15 geo_end_final.gen -dftb+ hessian.out`

I am getting the following error,

```
[ERROR] Program stopped due to fatal error
-2- Could not read hessian from 'hessian.out'
-1- io_reader_readHessian: Could not find $hessian data group
```

**Comment by MtoLStoN** [comment]
Thank you for reporting this. It seems, that there may be problems with reading the commandline argument due to the '+' sign in it, depending on the used environment. I prepared a PR, that changes this commandline argument to "--dftbplus", keeping the old behavior as an additional possibility to keep backward compatibility.

**Comment by ankur56** [comment]
@MtoLStoN Thank you for your response. 
I am also interested in computing the IR spectra. The IR submodule also uses `--dftbplus` argument. It would be really helpful if you could check if it's working as expected or not. Unfortunately, DFTB+ is not generating the `born.out` file for some reason, so I can't check the IR submodule.

**Comment by MtoLStoN** [comment]
@ankur56 I can confirm that the IR submodule works as expected from our side. Regarding the ``xtb thermo``, you may want to try our [bleed](https://github.com/grimme-lab/xtb/releases/tag/bleed) version, which has PR #847 included.
